USE [master]
GO

/****** Object:  Database [AjaxSamples]    Script Date: 03/08/2013 21:24:21 ******/
CREATE DATABASE [AjaxSamples] 


ALTER DATABASE [AjaxSamples] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [AjaxSamples] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [AjaxSamples] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [AjaxSamples] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [AjaxSamples] SET ARITHABORT OFF 
GO

ALTER DATABASE [AjaxSamples] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [AjaxSamples] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [AjaxSamples] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [AjaxSamples] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [AjaxSamples] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [AjaxSamples] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [AjaxSamples] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [AjaxSamples] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [AjaxSamples] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [AjaxSamples] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [AjaxSamples] SET  DISABLE_BROKER 
GO

ALTER DATABASE [AjaxSamples] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [AjaxSamples] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [AjaxSamples] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [AjaxSamples] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [AjaxSamples] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [AjaxSamples] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [AjaxSamples] SET  READ_WRITE 
GO

ALTER DATABASE [AjaxSamples] SET RECOVERY FULL 
GO

ALTER DATABASE [AjaxSamples] SET  MULTI_USER 
GO

ALTER DATABASE [AjaxSamples] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [AjaxSamples] SET DB_CHAINING OFF 
GO


---------------------------------------

USE [AjaxSamples]
GO

/****** Object:  Table [dbo].[UserRatings]    Script Date: 03/09/2013 20:40:33 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[UserRatings](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Rating] [smallint] NOT NULL,
 CONSTRAINT [PK_UserRatings] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

